### ISSUE TITLE
The implementation of soft_supconloss may be inconsistent with equation (8) in the published version

### ISSUE THREAD

**Issue by Ming-er** [TencentYoutuResearch/Classification-SemiCLS#7]
Thanks for sharing such a brilliant work. However, I am confused by the implementation of supconloss. 
In your paper, Equation (8) performs the foreground re-weighting multiplication (using w_{ij}) inside the log operation. However, in soft_supconloss.py, the re-weighting factor 'mask' is multiplied with 'log_prob' in line 103, and the later ('log_prob') is the results of 'z_i z_p / \tau' in practice, which means that w_{ij} is excluded outside the log operation.

**Comment by KaiWU5** [comment]
Sorry about the clerical error in equation (8). The w_ij should be outside of "log" for re-weighting purposes, and inside may incur nan loss when w_ij = 0. We will quickly straighten that out on Arxiv.
![image](https://user-images.githubusercontent.com/38367713/189293588-9640792b-3487-482e-b5cc-8b471d61b3aa.png)



Feel free to talk more details about our paper or further directions. Thank you.
