### ISSUE TITLE
Moco pretrained weight path

### ISSUE THREAD

**Issue by JongMokKim** [TencentYoutuResearch/Classification-SemiCLS#8]
Hi! Thank you for great work!

I want to reproduce the results in Semi-INat with MOCO pretrained weight.

Can I get the path or information about the moco pretrained weight you used?

In code, there is args.pretrained, but I can't find the path or information about it in README.

**Comment by KaiWU5** [comment]
Thanks for mentioning. I have uploaded to 
https://github.com/TencentYoutuResearch/Classification-SemiCLS/tree/main/pretrained_models

**Comment by JongMokKim** [comment]
Thank you for your kind reply!

**Comment by HyunjiEllenPak** [comment]
@KaiWU5 I downloaded above moco weights. but training with the pretrained weights didn't work in your code with semi-inat-2021 dataset. it showed me the error such as "_picle.UnpicklingError: invalid load key, 'v'". When I searched the error on google, some people said the uploaded weights on github  could be lost slightly. Thus, could you upload the moco pretrained weights through google drive or other drive platform?
